### ISSUE TITLE
`unable to convert check_ip_timeout to an int value` when importing a VM

### ISSUE THREAD

**Issue by UTF-8x** [xenserver/terraform-provider-xenserver#73]
Terraform version 1.9.8 (Windows)

Provider version 0.1.2

XenServer 8 (2024.0229)

**Steps to reproduce:**

 1. Add an empty VM block
    ```hcl
    resource "xenserver_vm" "vm" {}
    ```
 2. Try to import it
    ```shell
    tf import xenserver_vm.vm ec561a6e-8c82-b228-e064-1e6a41f4efd8
    ```

**Expected outcome:**

The VM is imported

**Actual outcome:**

The following error:

```
╷
│ Error: Unable to update VM resource model state
│
│ unable to convert check_ip_timeout to an int value
╵
```

Setting the value of `check_ip_timeout` manually before import makes no difference.

**Comment by acefei** [comment]
We will address this error. I am curious about your deployment scenario. Even if this import is successful, it will fail when applying main.tf as the VM block is empty.

**Comment by UTF-8x** [comment]
The goal here is actually to use [`terraform plan -generate-config-out`](https://developer.hashicorp.com/terraform/cli/commands/plan#generate-config-out-path) which fails for the same reason.

**Comment by acefei** [comment]
XSTF v0.2.0 has been released and it fixed this error. However, we did not verify the TF feature you mentioned with [terraform plan -generate-config-out](https://developer.hashicorp.com/terraform/cli/commands/plan#generate-config-out-path)
